# Generated by Django 5.2.7 on 2025-11-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city_code', models.CharField(db_index=True, max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='AT', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, max_length=1)),
                ('customer_id', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='app.address')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='app.appuser')),
            ],
        ),
    ]
