# Generated by Django 5.2.7 on 2025-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['first_name', 'last_name'], name='app_appuser_first_n_639269_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['customer_id'], name='app_appuser_custome_c3dd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['created'], name='app_appuser_created_78c46f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['points'], name='app_custome_points_7b652b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['last_activity'], name='app_custome_last_ac_20a7e6_idx'),
        ),
    ]
