# Generated by Django 5.2.7 on 2025-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appuser_app_appuser_first_n_639269_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city_code', 'city'], name='app_address_city_co_eaf430_idx'),
        ),
    ]
